/// Designation dropdown options
class DesignationOptions {
  static const List<String> values = [
    'Software Engineer',
    'Senior Software Engineer',
    'Lead Software Engineer',
    'Principal Software Engineer',
    'Software Architect',
    'Full Stack Developer',
    'Frontend Developer',
    'Backend Developer',
    'Mobile Developer',
    'DevOps Engineer',
    'Data Scientist',
    'Data Analyst',
    'Product Manager',
    'Project Manager',
    'Business Analyst',
    'QA Engineer',
    'UI/UX Designer',
    'Marketing Manager',
    'Sales Executive',
    'HR Manager',
    'Finance Manager',
    'Operations Manager',
    'Team Lead',
    'Technical Lead',
    'Manager',
    'Senior Manager',
    'Director',
    'Vice President',
    'CEO',
    'CTO',
    'Intern',
    'Associate',
    'Executive',
    'Specialist',
    'Consultant',
    'Other',
  ];
}
